---
- name: Run common workload analysis
  ansible.builtin.include_tasks: workload.yml
  when: report_scope_requires_common_workload_analysis | default(true) | bool

- name: Run common security and hygiene analysis
  ansible.builtin.include_tasks: security.yml
  when: report_scope_requires_common_security_analysis | default(true) | bool
