---
- name: Run common workload health and resilience analysis
  ansible.builtin.include_tasks: workload/health_and_resilience.yml

- name: Run common workload governance analysis
  ansible.builtin.include_tasks: workload/governance.yml

- name: Run common workload probe coverage analysis
  ansible.builtin.include_tasks: workload/probe_coverage.yml
