---
- name: Run Kubernetes core analysis
  ansible.builtin.include_tasks: core.yml

- name: Run Kubernetes provider analysis
  ansible.builtin.include_tasks: provider.yml

- name: Build Kubernetes capability profile analysis
  ansible.builtin.include_tasks: capability_profile.yml

- name: Build Kubernetes summary analysis
  ansible.builtin.include_tasks: summary.yml
