---
- name: Run core analysis
  ansible.builtin.include_tasks: core.yml

- name: Run workload analysis
  ansible.builtin.include_tasks: workload.yml

- name: Run security and configuration analysis
  ansible.builtin.include_tasks: security.yml

- name: Run observability and performance analysis
  ansible.builtin.include_tasks: observability.yml

- name: Build summary analysis
  ansible.builtin.include_tasks: summary.yml
