---
# vars file for openshift-healthcheck/
oscp_api_url: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_API_URL') }}"
oscp_user: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_USER') }}"
oscp_password: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_PASSWORD') }}"
oscp_token: "{{ lookup('ansible.builtin.env', 'OPENSHIFT_TOKEN') }}"

# CSS styling for navbar: menu width, failed/missing colors
nav_width: 200px
failed_style: 'color:orangered'
missing_style: 'color:grey;text-decoration:line-through'

# Email options
send_email: false
smtp_host: "smtp.example.com"
smtp_port: 25
mail_from: "healthcheck@example.com"
mail_to: "platform@example.com"
mail_subject: "OpenShift health check report"
# Uncomment these if authentication is required
#smtp_user:
#smtp_pass: