---
- name: Run review-domain API and build inventory analysis
  ansible.builtin.include_tasks: review_domains/api_build_inventory.yml

- name: Run review-domain compliance analysis
  ansible.builtin.include_tasks: review_domains/compliance.yml

- name: Run review-domain backup and remediation analysis
  ansible.builtin.include_tasks: review_domains/backup_and_remediation.yml

- name: Run review-domain SCC analysis
  ansible.builtin.include_tasks: review_domains/scc.yml
