---
- name: Run supportability evidence summary analysis
  ansible.builtin.include_tasks: supportability_evidence/summaries.yml

- name: Run supportability evidence findings analysis
  ansible.builtin.include_tasks: supportability_evidence/findings.yml
